// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyivrndsnkwfmfbbwvsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5aXZybmRzbmt3Zm1mYmJ3dnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjQwMjksImV4cCI6MjA2NjgwMDAyOX0.tjiCnP6dm4a6bo0B7BDcSJxCws-K79w_tbtJNYwsU5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});